// Generated by CoffeeScript 1.6.1
var Game;

Game = (function() {

  function Game(doc) {
    this.doc = doc != null ? doc : document;
  }

  Game.prototype.init = function() {
    this.canvas = this.doc.createElement('canvas');
    return this.doc.body.appendChild(this.canvas);
  };

  Game.prototype.resize = function(h, w) {
    if (h == null) {
      h = '320';
    }
    if (w == null) {
      w = '240';
    }
    this.canvas.height = h;
    return this.canvas.width = w;
  };

  Game.prototype.context = function(dim) {
    if (dim == null) {
      dim = '2d';
    }
    return this.canvas.getContext(dim);
  };

  return Game;

})();
