// Generated by CoffeeScript 1.6.1
var TheLoop;

window.onload = function(e) {
  var life;
  console.log('Window loaded #{e}');
  life = new Life();
  life.start();
  return TheLoop(life);
};

TheLoop = function(l) {
  l.tick();
  return setTimeout(TheLoop, l._tick, l);
};
